# Generated by Django 6.1.1 on 2026-10-01 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmacia', '0002_insumo_activo'),
    ]

    operations = [
        migrations.AddField(
            model_name='insumo',
            name='imagen_url',
            field=models.URLField(blank=True, default='https://images.unsplash.com/photo-1584308666744-24d5e4a7732a?w=500&q=80', max_length=800, null=True),
        ),
    ]
