# Generated by Django 6.1.1 on 2026-10-01 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmacia', '0003_insumo_imagen_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='insumo',
            name='imagen_url',
            field=models.CharField(blank=True, default='/static/farmacia/img/default.jpg', max_length=800, null=True),
        ),
    ]
